addSbtPlugin("org.scoverage"  % "sbt-scoverage"  % "2.2.2")
addSbtPlugin("ch.epfl.scala"  % "sbt-scalafix"   % "0.11.1")
addSbtPlugin("org.scalameta"  % "sbt-scalafmt"   % "2.5.2")
addSbtPlugin("com.eed3si9n"   % "sbt-assembly"   % "2.1.5")
addSbtPlugin("com.github.sbt" % "sbt-ci-release" % "1.5.12")
