name: Scala CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: hseeberger/scala-sbt:11.0.20_1.9.7_3.3.1
      options: --user root

    steps:
      - uses: actions/checkout@v3

      - name: Cache sbt
        uses: actions/cache@v3
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
            ~/.coursier/cache/v1
            ~/.cache/coursier/v1
            ~/Library/Caches/Coursier/v1
            target
          key: ${{ runner.os }}-sbt-cache-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}
          restore-keys: |
            ${{ runner.os }}-sbt-cache-

      - name: Run tests with coverage
        run: sbt clean coverage test coverageReport

      - name: Check coverage
        run: |
          COVERAGE=$(cat target/scala-3.3.1/scoverage-report/scoverage.xml | grep "statement-rate" | cut -d'"' -f2)
          if (( $(echo "$COVERAGE < 90" | bc -l) )); then
            echo "Coverage is below 90%: $COVERAGE%"
            exit 1
          fi
          echo "Coverage is $COVERAGE%"

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: target/scala-3.3.1/scoverage-report/
          retention-days: 14

  lint:
    runs-on: ubuntu-latest
    container:
      image: hseeberger/scala-sbt:11.0.20_1.9.7_3.3.1
      options: --user root

    steps:
      - uses: actions/checkout@v3

      - name: Cache sbt
        uses: actions/cache@v3
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
            ~/.coursier/cache/v1
            ~/.cache/coursier/v1
            ~/Library/Caches/Coursier/v1
            target
          key: ${{ runner.os }}-sbt-cache-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}
          restore-keys: |
            ${{ runner.os }}-sbt-cache-

      - name: Check formatting
        run: sbt scalafmtCheckAll