name: Scala CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Improve SBT performance
  SBT_OPTS: >-
    -Xmx2G
    -XX:+UseG1GC
    -XX:+UseStringDeduplication
    -Xss2M
  # Coursier cache optimization
  COURSIER_CACHE: ~/.cache/coursier

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'sbt'

      - name: Setup SBT
        uses: olafurpg/setup-scala@v14
        with:
          java-version: adopt@1.11
          
      - name: Cache Coursier
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/coursier
            ~/.sbt
          key: ${{ runner.os }}-sbt-coursier-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}-${{ hashFiles('project/plugins.sbt') }}
          restore-keys: |
            ${{ runner.os }}-sbt-coursier-

      - name: Run tests with coverage
        run: sbt clean coverage test coverageReport

      - name: Check coverage
        run: |
          COVERAGE=$(cat target/scala-3.3.1/scoverage-report/scoverage.xml | grep "statement-rate" | cut -d'"' -f2)
          if (( $(echo "$COVERAGE < 90" | bc -l) )); then
            echo "Coverage is below 90%: $COVERAGE%"
            exit 1
          fi
          echo "Coverage is $COVERAGE%"

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: target/scala-3.3.1/scoverage-report/
          retention-days: 14

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'sbt'

      - name: Setup SBT
        uses: olafurpg/setup-scala@v14
        with:
          java-version: adopt@1.11
          
      - name: Cache Coursier
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/coursier
            ~/.sbt
          key: ${{ runner.os }}-sbt-coursier-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}-${{ hashFiles('project/plugins.sbt') }}
          restore-keys: |
            ${{ runner.os }}-sbt-coursier-

      - name: Check formatting
        run: sbt scalafmtCheckAll